config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :musics, :beers

  get     "/movies",            to: "movies#index",   as: :movies
  post    "/movies",            to: "movies#create"

  get     "/movies/new",        to: "movies#new",     as: :new_movie

  get     "/movies/:id",        to: "movies#show",    as: :movie
  patch   "/movies/:id",        to: "movies#update"
  put     "/movies/:id",        to: "movies#update"
  delete  "/movies/:id",        to: "movies#destroy"

  get     "/movies/:id/edit",   to: "movies#edit",    as: :edit_movie

  post    "/movies/:id/upvote", to: "movies#upvote",  as: :upvote_movie

  post    "/musics/:id/upvote", to: "musics#upvote",  as: :upvote_music

  post    "/beers/:id/upvote", to: "beers#upvote",  as: :upvote_beer

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  before_save :default_values

  def self.sorted_by_votes
    order(votes: :desc)
  end

  def self.top_ten
    sorted_by_votes.first(10)
  end

  def default_values
    self.votes ||= 0
  end

  def add_one_vote
    self.votes += 1
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  before_save :default_values

  def self.sorted_by_votes
    order(votes: :desc)
  end

  def self.top_ten
    sorted_by_votes.first(10)
  end

  def default_values
    self.votes ||= 0
  end

  def add_one_vote
    self.votes += 1
  end

end

app/models/music.rb
class Music < ActiveRecord::Base
  before_save :default_values

  def self.sorted_by_votes
    order(votes: :desc)
  end

  def self.top_ten
    sorted_by_votes.first(10)
  end

  def default_values
    self.votes ||= 0
  end

  def add_one_vote
    self.votes += 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  # index, show, edit, update, new, create, destroy
  def index
    @beers = Beer.sorted_by_votes
  end

  def show
    @beer = Beer.find(params.require(:id))
  end

  def edit
    @beer = Beer.find(params.require(:id))
    render :template => "/shared/edit_new", :locals => { :obj => @beer, :person_att => "Brewery" }
  end

  def update
    @beer = Beer.find(params.require(:id))
    if @beer.update(beer_params)
      redirect_to beer_path
    else
      render :template => "/shared/edit_new", :locals => { :obj => @beer, :person_att => "Brewery" }
    end
  end

  def new
    @beer = Beer.new
    render :template => "/shared/edit_new", :locals => { :obj => @beer, :person_att => "Brewery" }
  end

  def create
    if Beer.create(beer_params)
      redirect_to beers_path
    else
      render :template => "/shared/edit_new", :locals => { :obj => @beer, :person_att => "Brewery" }
    end
  end

  def destroy
    @beer = Beer.find(params.require(:id))
    if @beer.destroy
      redirect_to beers_path
    else
      render :show
    end
  end

  def upvote
    @beer = Beer.find(params.require(:id))
    @beer.add_one_vote
    if @beer.save
      redirect_to request.referer
    else
      raise "ERROR"
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name,:description,:attributed_to)
  end

  def current_beer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.top_ten
    @beers = Beer.top_ten
    @musics = Music.top_ten
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # index, show, edit, update, new, create, destroy
  def index
    @movies = Movie.sorted_by_votes
  end

  def show
    find_movie
  end

  def edit
    find_movie
    render :template => "/shared/edit_new", :locals => { :obj => @movie, :person_att => "Director" }
  end

  def update
    find_movie
    if @movie.update(movie_params)
      redirect_to movie_path
    else
      render :template => "/shared/edit_new", :locals => { :obj => @movie, :person_att => "Director" }
    end
  end

  def new
    @movie = Movie.new
    render :template => "/shared/edit_new", :locals => { :obj => @movie, :person_att => "Director" }
  end

  def create
    if Movie.create(movie_params)
      redirect_to movies_path
    else
      render :template => "/shared/edit_new", :locals => { :obj => @movie, :person_att => "Director" }
    end
  end

  def destroy
    find_movie
    if @movie.destroy
      redirect_to movies_path
    else
      render :show
    end
  end

  def upvote
    find_movie
    @movie.add_one_vote
    if @movie.save
      redirect_to request.referer
    else
      raise "ERROR"
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:name,:description,:attributed_to)
  end

  def find_movie
    @movie = Movie.find(params.require(:id))
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  # index, show, edit, update, new, create, destroy
  def index
    @musics = Music.sorted_by_votes
  end

  def show
    @music = Music.find(params.require(:id))
  end

  def edit
    @music = Music.find(params.require(:id))
    render :template => "/shared/edit_new", :locals => { :obj => @music, :person_att => "Artist" }
  end

  def update
    @music = Music.find(params.require(:id))
    if @music.update(music_params)
      redirect_to music_path
    else
      render :template => "/shared/edit_new", :locals => { :obj => @music, :person_att => "Artist" }
    end
  end

  def new
    @music = Music.new
    render :template => "/shared/edit_new", :locals => { :obj => @music, :person_att => "Artist" }
  end

  def create
    if Music.create(music_params)
      redirect_to musics_path
    else
      render :template => "/shared/edit_new", :locals => { :obj => @music, :person_att => "Artist" }
    end
  end

  def destroy
    @music = Music.find(params.require(:id))
    if @music.destroy
      redirect_to musics_path
    else
      render :show
    end
  end

  def upvote
    @music = Music.find(params.require(:id))
    @music.add_one_vote
    if @music.save
      redirect_to request.referer
    else
      raise "ERROR"
    end
  end

  private

  def music_params
    params.require(:music).permit(:name,:description,:attributed_to)
  end

  def current_music
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/beers/index.html.erb
<h2>Beers</h2>

<table class="table-hover table-responsive col-sm-12">
  <tr>
    <td>Votes</td>
    <td>Album Name</td>
    <td>Upvote</td>
  </tr>
  <% @beers.each do |beer| %>
  <tr>
    <td><%= beer.votes %></td>
    <!-- I googled the link_to stuff below and it works but it seems v magical -->
    <td><%= link_to "#{beer.name}", beer %></td>
    <td><%= link_to upvote_beer_path(beer), {:method => "POST", :class => "btn btn-default btn-md"} do %>
      <span class="glyphicon glyphicon-thumbs-up"></span>
    <% end %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Add New Beer", new_beer_path, :class => "btn btn-info" %>

app/views/beers/show.html.erb
<h1><%= @beer.name %></h1>
<h2>Brewery: <%= @beer.attributed_to %></h2>
<div class=description>
  <%= @beer.description %>
</div>
<div class="row">
  <div class="col-xs-2">
  Votes: <%= @beer.votes %>
  </div>
  <div class="col-xs-10">

  </div>
</div>
<div class="btn-group">
  <%= link_to upvote_beer_path(@beer), {:method => "POST", :class => "btn btn-default btn-md"} do %>
    <span class="glyphicon glyphicon-thumbs-up"></span>
  <% end %>
  <%= link_to "Delete", beer_path(@beer), {:method => "DELETE", :class => "btn btn-default"} %>
  <%= link_to "Edit #{@beer.name}", edit_beer_path(@beer), :class => "btn btn-default" %>
</div>
<div class="other-buttons">

<span class="view-all"><%= link_to "View All Beers", beers_path %></span>
<span class="view-everything"><%= link_to "View Everything", root_path %></span>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="movies col-sm-4">
    <h2>Movies</h2>
      <%= render "shared/top_ten_list", :objs=>@movies %>
      <div class="btn-group">
      <%= link_to movies_path, :class=>"btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-facetime-video"></span>
        view more
      <% end %>
      <%= link_to new_movie_path, :class => "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-plus"></span>
        add new
      <% end %>
    </div>
  </div><!-- /class movies col -->
  <div class="music col-sm-4">
    <h2>Musics</h2>
      <%= render "shared/top_ten_list", :objs=>@musics %>
      <div class="btn-group">
      <%= link_to musics_path, :class=>"btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-headphones"></span>
      view more
      <% end %>
      <%= link_to new_music_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-plus"></span>
      add new
      <% end %>
      </div>
  </div><!-- /class music col -->

  <div class="beer col-sm-4">
    <h2>Beers</h2>
      <%= render "shared/top_ten_list", :objs=>@beers %>
      <div class="btn-group">
      <%= link_to beers_path, :class=>"btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-heart"></span>
      view more
      <% end %>
      <%= link_to new_beer_path, :class => "btn btn-default btn-sm" do %>
      <span class="glyphicon glyphicon-plus"></span>
      add new
      <% end %>
      </div>
  </div><!-- /class beer col -->

</div><!-- /row -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RankyPanky</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href='http://fonts.googleapis.com/css?family=Permanent+Marker' rel='stylesheet' type='text/css'></head>
  <link href='http://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
<body>
  <div class="container-fluid">
    <div class="header">
      <div class="brand">
        <h1><%= link_to "Ranky Panky", root_path %></h1>
        <h2>ranking the best of things Bri likes</h2>
      </div>
    </div><!-- /class header -->
  </div><!-- /class container-fluid -->
<div class="container">
  <div class="row">
    <div class="main col-xs-12">
      <%= yield %>
    </div> <!-- /main col -->
  </div><!-- /row -->
</div><!-- /class container -->


</body>
</html>

app/views/movies/edit.html.erb
<%= form_for @movie, :html => {:role => "form"} do |f| %>
  <div class="form-group">
  <%= f.label :name %>:
  <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :attributed_to %>:
  <%= f.text_field :attributed_to, :class => "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :description %>:
  <%= f.text_area :description, :class => "form-control" %>
  </div>

  <%= f.submit "Submit", :class => "btn btn-primary" %>
<% end %>

app/views/movies/index.html.erb
<h2>Movies</h2>

<table class="table-hover table-responsive col-sm-12">
  <tr>
    <td>Votes</td>
    <td>Name</td>
    <td>Upvote</td>
  </tr>
  <% @movies.each do |movie| %>
  <tr>
    <td><%= movie.votes %></td>
    <!-- I googled the link_to stuff below and it works but it seems v magical -->
    <td><%= link_to "#{movie.name}", movie %></td>
    <td><%= link_to upvote_movie_path(movie), {:method => "POST", :class => "btn btn-default btn-md"} do %>
      <span class="glyphicon glyphicon-thumbs-up"></span>
    <% end %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Add New Movie", new_movie_path, :class => "btn btn-info" %>

app/views/movies/show.html.erb
<h1><%= @movie.name %></h1>
<h2>Directed by: <%= @movie.attributed_to %></h2>

<div class=description>
  <%= @movie.description %>
</div>

<div class="row">
  <div class="col-xs-2">
  Votes: <%= @movie.votes %>
  </div>
  <div class="col-xs-10">

  </div>
</div>

<div class="btn-group">
  <%= link_to upvote_movie_path(@movie), {:method => "POST", :class => "btn btn-default btn-md"} do %>
    <span class="glyphicon glyphicon-thumbs-up"></span>
  <% end %>
  <%= link_to "Delete", movie_path(@movie), {:method => "DELETE", :class => "btn btn-default"} %>
  <%= link_to "Edit #{@movie.name}", edit_movie_path(@movie), :class => "btn btn-default" %>
</div>

<div class="other-buttons">
<span class="view-all-movies"><%= link_to "View All Movies", movies_path %></span>
<span class="view-everything"><%= link_to "View Everything", root_path %></span>
</div>

app/views/musics/index.html.erb
<h2>Musics</h2>

<table class="table-hover table-responsive col-sm-12">
  <tr>
    <td>Votes</td>
    <td>Album Name</td>
    <td>Upvote</td>
  </tr>
  <% @musics.each do |music| %>
  <tr>
    <td><%= music.votes %></td>
    <!-- I googled the link_to stuff below and it works but it seems v magical -->
    <td><%= link_to "#{music.name}", music %></td>
    <td><%= link_to upvote_music_path(music), {:method => "POST", :class => "btn btn-default btn-md"} do %>
      <span class="glyphicon glyphicon-thumbs-up"></span>
    <% end %></td>
  </tr>
  <% end %>
</table>

<%= link_to "Add New Music", new_music_path, :class => "btn btn-info" %>

app/views/musics/show.html.erb
<h1><%= @music.name %></h1>
<h2>Artist: <%= @music.attributed_to %></h2>
<div class=description>
  <%= @music.description %>
</div>
<div class="row">
  <div class="col-xs-2">
  Votes: <%= @music.votes %>
  </div>
  <div class="col-xs-10">

  </div>
</div>
<div class="btn-group">
  <%= link_to upvote_music_path(@music), {:method => "POST", :class => "btn btn-default btn-md"} do %>
    <span class="glyphicon glyphicon-thumbs-up"></span>
  <% end %>
  <%= link_to "Delete", music_path(@music), {:method => "DELETE", :class => "btn btn-default"} %>
  <%= link_to "Edit #{@music.name}", edit_music_path(@music), :class => "btn btn-default" %>
</div>
<div class="other-buttons">

<span class="view-all"><%= link_to "View All Musics", musics_path %></span>
<span class="view-everything"><%= link_to "View Everything", root_path %></span>
</div>

app/views/shared/_top_ten_list.html.erb
<% objs.each do |obj| %>
<div class="top-ten-list">
  <span class="obj-name"><%= link_to "#{obj.name}", obj %></span>
  <span class="obj-votes">Votes: <%= obj.votes %></span>
</div><!-- /class top-ten-list   -->
<% end %>

app/views/shared/_upvote_button.html.erb
<%= link_to upvote_movie(movie), {:method => "POST", :class => "btn btn-default btn-md"} do %>
  <span class="glyphicon glyphicon-thumbs-up"></span>
<% end %>

app/views/shared/edit_new.html.erb
<%= form_for obj, :html => {:role => "form"} do |f| %>
  <div class="form-group">
  <%= f.label :name %>:
  <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :attributed_to, person_att.capitalize %>:
  <%= f.text_field :attributed_to, :class => "form-control" %>
  </div>

  <div class="form-group">
  <%= f.label :description %>:
  <%= f.text_area :description, :class => "form-control" %>
  </div>

  <%= f.submit "Submit", :class => "btn btn-primary" %>
<% end %>